[package]
name = "chainrail-database"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
chainrail-common = { workspace = true, features = ["sqlx"] }
sqlx.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
bigdecimal.workspace = true
tracing.workspace = true
thiserror.workspace = true
async-trait.workspace = true
